### ISSUE TITLE
Slack integration

### ISSUE THREAD

**Issue by torkilm** [heimdalit/deling#30]
Possibility to share on slack

**Comment by egilkh** [comment]
Please provide an example of how this is done?

**Comment by torkilm** [comment]
https://api.slack.com/methods/chat.postMessage

**Comment by egilkh** [comment]
That method is not meant to be consumed by the public. It would require deling.js to know enough info to post any message to the channel and slack account.

This in turn means you have now opened up for any one that knows how to search your site to post lovely messages to your slack.

Closing.
