### ISSUE TITLE
Better readme

### ISSUE THREAD

**Issue by nagilum** [heimdalit/deling#9]
The readme file should be a bit better to make it easier to implement. Throw in a few examples as well as screenshots of each example. Would be nice :)

**Comment by egilkh** [comment]
Agreed.

Maybe we might get away by linking to the demo in the readme instead of screenshots?

**Comment by nagilum** [comment]
Might work.

**Comment by egilkh** [comment]
To clarify: Add usage examples in readme with code and explanations but instead of providing a screenshot link to the relevant rendered example on the demo page.

**Comment by nagilum** [comment]
That should do it.

**Comment by egilkh** [comment]
Project dead. Deading issues.
